### ISSUE TITLE
Error when create BrowserDriverBuilder with chrome

### ISSUE THREAD

**Issue by antfig-olx** [athena-oss/php-fluent-webdriver-client#3]
When I create a new instance off BrowserDriverBuilder with type chrome a receive an error.

**Example:**

```
$driver = (new BrowserDriverBuilder('http://localhost:4444/wd/hub'))
                 ->withType('chrome');
```

**Error:**

```
TypeError: Argument 1 passed to Facebook\WebDriver\Chrome\ChromeOptions::addArguments() must be of the type array, 
null given, called in ./vendor/athena-oss/php-fluent-webdriver-client/src/Browser/BrowserDriverBuilder.php on line 239
```

**One solution I found was that I can pass chrome option like:**

```
$driver = (new BrowserDriverBuilder('http://localhost:4444/wd/hub'))
            ->withType('chrome')->withChromeOptionsArguments([]);
```

But I think the best solution would be to add a default value to `$chromeOptions` var in the `BrowserDriverBuilder.php` file

Tested in version: v0.7.2

**Comment by ghost** [comment]
@antfig-fixeads I think we could use your idea of having a default value to `$chromeOptions`. Can you please create a PR with your change?

**Comment by antfig-olx** [comment]
@caiomoritz yes I can do that, no problem

**Comment by antfig-olx** [comment]
@caiomoritz you can close the issue I guess :) 
You will create some new tag? because I have my composer with `^0.7` and don't update the code with latests changes

**Comment by ghost** [comment]
@antfig-fixeads please check release v0.7.3
